exp_root: ''
stage: texture
model:
    use_dmtet_network: false
    use_color_network: true
    tet_offset_scale: 0.
    tet_grid_volume: 5e-8
    tet_num_subdiv: 1
    render_ssaa: 4
    use_can_pose_space: True
train:
    lock_geo: True
    iters: 7000
    normal_sample_ratio: 0.
    radius_range: [0.7, 1.3]
    height_range: [-0.4, 0.4]
    theta_range: [60, 120]
    phi_diff: 30
    face_sample_ratio: 0.3
    face_height_range: [0., 0.]
    face_radius_range: [0.3, 0.4]
    face_phi_diff: 30
    face_theta_range: [90, 90]
    face_phi_range: [-90, 90]
    lambda_lap: 0.
    lambda_sil: 0.
    lambda_normal: 0.
    lambda_recon: 10000.
    lambda_color_chamfer: 1e6
    color_chamfer_step: 5000
    crop_for_lpips: true
test:
    save_mesh: true
    test: False
data:
    load_input_image: True
    load_front_normal: True
    load_back_normal: True
    load_result_mesh: True
    load_apose_mesh: True
    load_occ_mask: True
guidance:
    use_view_prompt: True
    guidance_scale: 100.
    step_range: [0.02, 0.25]
